### ISSUE TITLE
Module Request: Soundcraft ui12 / ui16 / ui24

### ISSUE THREAD

**Issue by startmedia001** [bitfocus/companion-module-soundcraft-ui#1]
Remote-Control the ui series from soundcraft, a digital multichanel audiomixer

platform independent

I dont know about a API, but the mixer itself provides a html5 interface wich can be controlled with a standard browser. The mixer has a buildin W-LAN acesspoint and ethernet-port (RJ45)
https://www.soundcraft.com/en/products/ui16

Control the Mixer itself
Activate Mutegroups
Control the buildin Audioplayer (USB-Port)
... same usecases like the x32 from behringer / midas

**Comment by whizkidTRW** [comment]
What about the SI series? I have an SI-Impact I’d love to do the same thing with. . . Just mute a channel or two.

**Comment by TheMrPoseidon** [comment]
@whizkidTRW Hi, a short online research reveals that Soundcraft used a different protocol for the Si-series. It's based on the HiQnet protocol (see also bitfocus/companion-module-requests#174) which isn't anywhere near the protocol used in Soundcraft Ui mixers.

**Comment by kintaro829** [comment]
@TheMrPoseidon Is there a working plugin for Elgato's Stream Deck? For example, I would like to mute my headphones 1/2 or set back to 30% volume, start/stop multitrack recording, mute individual channels, etc.

I've found usefull information for all parameter etc. but have no skills in programming.

Here is a online demo for the mixer interface: http://www.soundcraft.com/ui24-software-demo/mixer.html
With CTRL-Shift-J (Chrome) you can open the JS-Console to track which paramter will be affected. You can activate the log 'enableLog();'.

I can you send more information from another forum if you want.

**Comment by TheMrPoseidon** [comment]
@kintaro829 Thanks to @fmalcher we are working on a big release which should cover most of your requirements. Please be a little patience. I hope changes are merged soon. @fmalcher started an idependent typescript library which he is integrating in this companion module. As far as I can tell the next release should be any time soon.

**Comment by kintaro829** [comment]
@TheMrPoseidon Thank you very much for this information. I am already excited. :)

@fmalcher Thank you for the awesome job!

Where will it be available for download? Or will you inform here when the first release is out?

**Comment by fmalcher** [comment]
@kintaro829 The module has now been merged into the companion core. You can also use it in your current running companion instance: Go to the companion root folder and navigate to `lib/module/soundcraft-ui` from there. Pull the git sub-repo from the latest master. Then restart companion. 🙂
If you have any feedback or feature requests, please let me know or create an issue in the module repo. Thanks!

> I would like to mute my headphones 1/2 or set back to 30% volume, start/stop multitrack recording, mute individual channels

Except for multitrack recording, all of this is possible!

**Comment by kintaro829** [comment]
@fmalcher Thank you. I'm totally new here and need a little bit of help. Is this the right repo: https://github.com/fmalcher/companion-module-soundcraft-ui ? How can i pull a sub-repo? Download as zip file?
Companion is a software i can use with the stream deck (https://bitfocus.io/companion/)?

**Comment by fmalcher** [comment]
@kintaro829 This one here is the right repo. The latest `master` is the version you need.
The newest version of this module is not part of the latest companion release yet. There are two variants for you now: 1.) wait for the next release, then it's just "install and run" or 2.) play around a bit and pull the subrepo as described above. Since the subrepo is already part of companion, it should be enough to find the respective folder and do a `git checkout master` and `git pull`.

You should join the Slack workspace and we can discuss things there!

**Comment by kintaro829** [comment]
@fmalcher Sorry for my beginner questions, but how do I join your/the Slack workspace? You must know i'm newbie and totally overwhelmed with all your informations 😄 

I am not (!) a programmer and have watched videos on how to use Git. 🤣 

Worst case, I wait for a version that can be installed. I'm just a user. 😅

**Comment by fmalcher** [comment]
@kintaro829 You can find the Slack invite link on the Companion website in the footer: https://bitfocus.io/companion/
Please let's continue all discussion and questions there so we don't pollute this issue here. 🙂
I think the best for you would be to wait for the next Companion release with this module included.

**Comment by rozruba** [comment]
Hey, I saw your project and I'm very interest in it, but documentation for user is not very clearly. I'm not a programist, I'm just a audio guy which like'd to use the stream deck with ui24r. How to I do it, cause I don't understand it still.

**Comment by fmalcher** [comment]
> Hey, I saw your project and I'm very interest in it, but documentation for user is not very clearly. I'm not a programist, I'm just a audio guy which like'd to use the stream deck with ui24r. How to I do it, cause I don't understand it still. 

Thanks for your message! You need to install Bitfocus Companion. It includes the module for the Soundcraft Ui series (among lots and lots of other hardware). After installing Companion, it offers you a web interface to configure buttons with actions and feedbacks.
If you have any further questions, please join the official Bitfocus Community Slack channel. There are many people over there that are happy to help 😊

**Comment by TkachVova** [comment]
I recently found this Elgato stream deck plugin which allows sending custom commands to Soundcraft mixers and has volume control action. It worked well for me for the things I needed: https://marketplace.elgato.com/product/soundcraft-control-cc0efce0-f615-4fc7-bba0-073299873077

**Comment by fmalcher** [comment]
@TkachVova Good to know!
The Companion module for Soundcraft Ui covers most of the mixer functions – and it's free. Is there any missing feature that made you choosing the pricey plugin from the Elgato Store?
