### ISSUE TITLE
Add audio recorder

### ISSUE THREAD

**Issue by TheMrPoseidon** [bitfocus/companion-module-soundcraft-ui#15]
Soundcraft UI devices are capable of recording the master feed onto an usb stick. To includig this functionality it is required to add a recording and stoping action to the module. In additon to that it is required to recive the status if the device started the recoding or not, this needs the #3 to be closed.

**Comment by fmalcher** [comment]
This is not supported by the connection lib at the moment: https://github.com/fmalcher/soundcraft-ui/issues/41

**Comment by fmalcher** [comment]
Connection lib supports this now
