### ISSUE TITLE
Change media player's modi

### ISSUE THREAD

**Issue by TheMrPoseidon** [bitfocus/companion-module-soundcraft-ui#16]
The media player is capable of playing music in the following the modi (a) manual, (b) auto, (c) auto-shuffel. In order to add this functionality to our module we have to add a new action which allows chaning the modi

**Comment by fmalcher** [comment]
Is already supported by the connection lib, but there are no actions for this yet.

**Comment by fmalcher** [comment]
addressed and implemented in PR #17
