### ISSUE TITLE
`yarn install` warnings

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-soundcraft-ui#24]
When doing a `yarn update` a few warnings are being emitted for this module. It would be good to clean those up if possible.

```
lib/module/soundcraft-ui/
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "soundcraft-ui-connection > isomorphic-ws@4.0.1" has unmet peer dependency "ws@*".
[4/4] Building fresh packages...
success Saved lockfile.
$ yarn build
$ rimraf dist && yarn build:main
$ tsc -p tsconfig.build.json
```

package-lock.json should not be present as that is for npm, and companion enforces the use of yarn.

The unmet peer dependency may or may not be something that should be resolved. It probably should, but there could be a reason it has not been

**Comment by Julusian** [comment]
Additionally, the `yarn update` is generating some `yarn.lock` changes, so an updated version should be committed

**Comment by fmalcher** [comment]
Ah yes, thank you for pointing this out. I used NPM, in fact... 🤦🏻‍♂️
I don't get why the peer dep warning appears since `soundcraft-ui-connection` has `ws` installed: https://github.com/fmalcher/soundcraft-ui/blob/main/package.json#L52
