### ISSUE TITLE
Phantom power

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-soundcraft-ui#30]
Hey guys, 

Thanks for the amazing job upgrading this module!

I've found one more feature which would be great to have:

Phantom Power on/off 

Of course feedback would be a plus :)

**Comment by fmalcher** [comment]
@TheMrPoseidon IMO it's safe for most devices but it could also be harmful. That's the point where I'd vote against making this controllable through 3rd-party software.

**Comment by TheMrPoseidon** [comment]
@fmalcher +1 (same opinion) running older marcos could potentially cause hardware damage this way

**Comment by TheMrPoseidon** [comment]
I have a proposal to make, @fmalcher what about a textfield or checkbox to accept the risks of damage. Another solution is to ask other developers and their way of solving the problem

**Comment by fmalcher** [comment]
Thanks for your ideas, I think I understand the issue. 🙂
An additional confirmation checkbox sounds like a good idea to me.

Maybe one of you could find out whether there is any other companion module that has Phantom power control?

@DachsbauTV Can you please split this into two separate issues (effects control and phantom power).

**Comment by DachsbauTV** [comment]
Done :)

I've looked through all the behringer modules (Xair, X32, Wing) and unfortunately there is no module with phantom power function...

However, they have a lot of dynamic variables in there, which could be useful for your other issue with the variables :)

**Comment by fmalcher** [comment]
Created an issue in the connection library which will be the first step: https://github.com/fmalcher/soundcraft-ui/issues/53
