### ISSUE TITLE
Effect Control

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-soundcraft-ui#32]
Hey guys, 

Thanks for the amazing job upgrading this module!

I've found one more features which would be great to have:

Effects control (on/off) 
Maybe even parameter control (+/- XX% ? )

Of course feedback or variables for the values would be a plus :)

**Comment by fmalcher** [comment]
Can you tell me shortly, please, where I can find the effects on/off? 😅

**Comment by DachsbauTV** [comment]
oops sorry i wasn't clear enough
The easiest way to toggle the effects on and off for each channel would be in the "FX Sends" tab and via the Mute buttons on each channel and in each FX category (Reverb, Delay, Room)

![Screenshot 2021-04-01 at 12 19 13](https://user-images.githubusercontent.com/70434961/113280549-b9a92180-92e4-11eb-89f2-5190e33cb65f.jpg)

**Comment by DachsbauTV** [comment]
Thought the parameters are found in each individual channel page

**Comment by fmalcher** [comment]
Aah I see 😊 FX channel mute and FX bus mute already works in the current version, so maybe that's already everything you need? 😃

**Comment by DachsbauTV** [comment]
oh my bad! that should be it then! that's great. Sorry due to an injury I haven't really been working with the UI recently.

I will try it hopefully next week, but close this in the meantime. Thanks again!
