### ISSUE TITLE
Mute channel on AUX bus

### ISSUE THREAD

**Issue by fmalcher** [bitfocus/companion-module-soundcraft-ui#4]
At the moment, this module can only mute channels on the master bus.
The message sent to the mixer looks like this, where `9` is the channel number that can be configures through the companion action:

```
3:::SETD^i.9.mute^1
```

When setting mute on a fader for an AUX mix, the message is the following.
`9` is the channel number, `3` is the AUX bus:

```
3:::SETD^i.9.aux.3.mute^1
```

How can we manage to implement this functionality?
Two ideas:

### 1. Allow all channel input values
At the moment, only numbers are allowed as channel input values. If we also allow strings, the input could be `10.aux.4`.
However, since the internal channel index is zero-based, we would have to subtract the input numbers by one (as already done for single numbers)

### 2. Build a UI around it
Add an extra field for "bus" with possible values "master" and "aux".
Another field for the AUX bus number. The whole message will then be built from this info.

-----

Thank you for feedback! I'm happy to create a PR for this once there's a plan how we want this.
Idea 2 above would be my favorite, though.

**Comment by JeffreyDavidsz** [comment]
You can assign 2 (or more) variables to an action. So one field for channel one field for aux number. Substract 1 from each number to get the right command.
So look for a module who has the option on a action with more than one input. Like VICREO luisteren there is a combo command. See how that's setup. Make sure that you upgrade the version number in your pull request and the indentation is in tabs
