### ISSUE TITLE
Channel Delays

### ISSUE THREAD

**Issue by Fred-DTV** [bitfocus/companion-module-soundcraft-ui#47]
Another feature request 🙈

Would it be possible to add the delay setting plus a variable? 

We sometimes run into unfortunate lipsync issues, due to our wireless mics and admittedly cheap equipment, which we need to fix during a stream. 
So having a delay +XXms and delay -XXms button would make it easier for us to fix this on the fly

**Comment by fmalcher** [comment]
Added an issue in the connection lib which has to support this first: https://github.com/fmalcher/soundcraft-ui/issues/64

**Comment by fmalcher** [comment]
The connection library supports channel delays in the next release.
