### ISSUE TITLE
Lock UI?

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion-module-soundcraft-ui#52]
Hi @fmalcher ,

Do you think it would be possible to integrate the lock-ing (log out) of the UI into companion?
![Uploading Screenshot 2022-11-08 at 11.00.28.jpg…]()

I would like to create a timed trigger to have the UI locked in regular intervals.

**Comment by fmalcher** [comment]
I'm afraid that will not work. The master password and login/logout state are purely local. As long as there is no message sent over the network when a client logs out there is no way for us to lock a client remotely.
See also https://github.com/bitfocus/companion-module-soundcraft-ui/issues/49
