### ISSUE TITLE
Start/Stop Multitrack Recording

### ISSUE THREAD

**Issue by Fred-DTV** [bitfocus/companion-module-soundcraft-ui#61]
Hi @fmalcher 

Would it be possible for you to add a Multitrack Recording toggle?
It would be great to automate all my recordings (OBS/ATEM/Soundraft) to start at the same time.

**Comment by fmalcher** [comment]
issue in the connection lib: https://github.com/fmalcher/soundcraft-ui/issues/47

**Comment by Fred-DTV** [comment]
ah damn :/
Hopefully it will be possible in the announced firmware release

**Comment by fmalcher** [comment]
Sorry, I didn't elaborate: This is not a problem, I (or someone else) "just" have to implement this in the connection lib first. This issue here can stay open until the feature is available. It would be good to target v3 so that we can include it in this big new release.

**Comment by fmalcher** [comment]
@Fred-DTV Can you please contact me privately via Twitter, Mastodon or e-mail? 🙂 Thanks!
