### ISSUE TITLE
Support for enabling and disabling automix channels.

### ISSUE THREAD

**Issue by koalaraptor** [bitfocus/companion-module-soundcraft-ui#72]
Howdy!

Very happy with the module, works well.
I was thinking, since they implemented a terrible pre-fader automix in the UI series, if it was possible via your module to quickly enable and disable automix channels on either a or b for the automix?

So when two speakers are present i could have 1+2 active and the rest deactivated, and then while prepping 3+4, i could put them on b, and quickly switch A to B when they switch on stage kinda thing?
Also quickly adding extra channels to a live automix, so A group is active on stage with mic 1+2+3, but then 30 mins in i need to add 4 and later channel 8 because it's a remote call kind of thing?

The soundcraft is a great little rack mixer that i would love to use more, but the automix function is currently holding it back big time for me on the streaming market.

I thank you for your time and i hope you get what i mean :)

<img width="1726" alt="Screenshot 2023-09-26 at 11 13 21" src="https://github.com/bitfocus/companion-module-soundcraft-ui/assets/8500842/a7ef87e0-b039-4ee0-89ad-15e46447933f">

**Comment by fmalcher** [comment]
Thanks for your feature request!
It looks possible to implement this. However, I will have to add support to the underlying connection lib first, so I created an issue here: https://github.com/fmalcher/soundcraft-ui/issues/116

To get this done properly, a lot of things need to be considered and created. Once the connection lib is ready, we'll need to implement the necessary actions and feedbacks in this Companion module here.

I do not expect to get this finished by earlier than end of this year.

**Comment by koalaraptor** [comment]
Hello Fmalcher!

Thank you for the speedy reply, even just the fact that it's a tiny bit possible brings me hope 😄!

The time frame does not sound bad, even if there is a tiny bit of hope of a function like this existing, would mean i could start using my ui24r's again like the work horses that they are :)
