### ISSUE TITLE
Save Current Snapshot.

### ISSUE THREAD

**Issue by chrisrust** [bitfocus/companion-module-soundcraft-ui#76]
I can see this might be tricky as the ui asks for confirmation when you save a snapshot, but being able to ensure that the current snapshot is saved when I select a new snapshot would be very helpful for my workflow, especially in soundchecks when I may be switching between acts/snapshots.

If it needs a confirmation, maybe that could be provided as a separate function, to be used on button up. In my workflow confirmation is never an issue. Losing changes is definitely an issue.

**Comment by fmalcher** [comment]
Thanks for your feature request! If you (or somebody else) create a proper design for this necessary actions and data flow I could implement this. This includes the necessary actions (and possibly feedbacks) to be implemented as well as considerations around a confirmation action. I think that we could need both a confirmable save action and one that just overwrites the snapshot.

**Comment by fmalcher** [comment]
The underlying [connection library](https://github.com/fmalcher/soundcraft-ui) does not support snapshot/show save at the moment. This would be the first step to implement.

**Comment by fmalcher** [comment]
https://github.com/fmalcher/soundcraft-ui/issues/144

**Comment by fmalcher** [comment]
I just created the necessary functions in the connection lib. It is now possible to save a snapshot by name, and we can also update the current snapshot (because we know the names of current show and snapshot).

It has to be integrated into the Companion module now.
