### ISSUE TITLE
Gets mute on monitor when i put a chanel on sub group

### ISSUE THREAD

**Issue by Reugin** [bitfocus/companion-module-soundcraft-ui#77]
When i put one or two chanels on sub group it gets mute on monitors. Is this issue or there is some setting for this? Please help.

**Comment by fmalcher** [comment]
Does it have the same behavior in the web app? Then it's a bug in the mixer.
The Companion module sends the same commands as the web app.

If you suspect an issue with this module, please provide a step-by-step description of how we can reproduce it.
Thanks!
