### ISSUE TITLE
Can't edit the connection settings while connection is inactive

### ISSUE THREAD

**Issue by dominik34** [bitfocus/companion-module-soundcraft-ui#78]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It is not possible to edit a connection (e.g. change the IP-Address) when the device is not reachable or the connection is disabled.

Do I have to make a new connection rebuild everything I've done?

### Steps To Reproduce

1. Added a new connection (e.g. Soundcraft Ui with IP 192.168.1.10)
2. Build the Companion interface with all the Buttons accoring to this connection
3. The IP Adress of the Device (soundcraft Ui) change because of a network change (is now e.g. 192.168.3.x)
4. Can't update the connection to the new IP-Adress: Loading bar and "connection config unavaliable"

### Environment

```markdown
- OS: Windows 10
- Browser: Firefox
- Companion Version: 3.2.0 (+6663)
```

### Additional context

I remember, changing the connection-config was possibel in previous builds.

**Comment by dominik34** [comment]
Thanks for the clarification!

A workaround I've found for anyone facing this issue:
Export the config, open the file with a texteditor, search for "soundcraft" and change the IP Adress there.
Then import the config again an you'll be fine.

**Comment by fmalcher** [comment]
Thanks for the report! I will try to fix this next week. However, it will take a bit of time to have this released together with Companion.
