### ISSUE TITLE
Request for Multitrack "Activate Soundcheck" toggle on UI24R with feedback

### ISSUE THREAD

**Issue by samuraitheta** [bitfocus/companion-module-soundcraft-ui#80]
Hello!

First of all, THANK YOU SO MUCH for your hard work on this. Could you add a button to toggle the "Activate Soundcheck" button on the Multitrack page? It would also be great to have feedback to the button. 

Thank you!

**Comment by fmalcher** [comment]
This was relatively easy to solve since the underlying connection library already supported the soundcheck switch. 😊
