### ISSUE TITLE
Missing command:: soundcraft: Multitrack Recording: Record

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-soundcraft-ui#86]
I have now found the ability to control multitrack recording, which is great - thank you! Unfortunately, the command to **start recording** is missing. There is only Toggle Recording and Stop Recording.

If I want to start recording and I don't know what state it is in, then I'm missing a command

`Start Recording`

If it's already recording, nothing changes. If it is not already recording, the process will start. Analogously, it already works

`Stop Recording`

How can this be currently bypassed? Use a timed sequence of commands:
```
Stop Recording # stops recording if it is running
Toggle Recoeding # starts recording because the previous state was STOP
```

**Comment by fmalcher** [comment]
This is actually how the mixer works internally. 🙂 No matter which recording state we are in, the "Record" button always sends a `MTK_RECORD_TOGGLE` command. For the underlying connection library, I wanted to stay as close as possible to the mixer API without too much additional logic around it. This is why the Companion module only has a "Record Toggle", too.
However, I agree that this feels strange from the user perspective. I think we could add methods for "Start Recording" and "Stop Recording" in the connection lib and, of course, in the Companion module.
I created an issue over in the connection lib as a first step: https://github.com/fmalcher/soundcraft-ui/issues/133
