### ISSUE TITLE
Missing command:: soundcraft: Multitrack Recording: Config

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-soundcraft-ui#87]
![image](https://github.com/user-attachments/assets/7defa5c2-2073-465e-b527-c11b9b2f7b75)

I'm not sure if Soundcraft Mix supports remote commands for this, but if so, please implement MULTITRACK CONFIG. The command allows you to choose which track to include in the recording.

In the command, it will be possible to enter the channel number and choose one of the options:
* Enabled
* Disabled
* Toggle

USE CASES:
In our podcast studio, the number of guests changes and thus the number of connected microphones. This command will allow me to choose on the streamdeck which microphones should be UNMUTE and mainly which should be recorded to the multitrack.

Thank you.

**Comment by fmalcher** [comment]
I created an issue over in the connection lib, which is always the first to be implemented: https://github.com/fmalcher/soundcraft-ui/issues/134

**Comment by fmalcher** [comment]
![Screenshot 2024-07-31 at 11 38 33](https://github.com/user-attachments/assets/2138e0f9-2d22-468b-a66c-1f0e94d8badb)
![Screenshot 2024-07-31 at 11 38 43](https://github.com/user-attachments/assets/6611ba91-4b9e-4e1e-b21b-4dd47bfc4812)
