### ISSUE TITLE
[BUG] soundcraft: Multitrack Recording: Stop

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-soundcraft-ui#89]
Function `soundcraft: Multitrack Recording: Stop` does something unexpected. When I call the function, the MTR sitll continues recording and I get errror message:

![image](https://github.com/user-attachments/assets/ed8ee8cc-a7cc-45b5-a782-092b96b79e1e)
![image](https://github.com/user-attachments/assets/8ac66959-2987-4af6-8ffb-711b7b8ae4a0)

**Comment by fmalcher** [comment]
You have to use the "Multitrack Recording: Record Stop" action. The "Stop" action does the same as the stop button in the UI which is disabled when recording is active.

**Comment by fmalcher** [comment]
Btw, it looks like the record toggle and channel selection work as expected?

**Comment by Suenee** [comment]
> Multitrack Recording: Record Stop

Oh, I can already see the difference. I'll admit it's confusing to me. By there being SoundCract: Multitrack Play: *, so if I would expect "STOP" for playback to be in the same group, not under MTR.

**Comment by Suenee** [comment]
> Btw, it looks like the record toggle and channel selection work as expected?

If you're asking about #87, I haven't tried it yet because I can't make my own build and I'm waiting for it to come out as an official Companion pack. Is there any way to speed it up / bypass it please?

Thanks a lot for your work! :-)

PS: If it works, I will gladly send a donation of 500 CZK.
