### ISSUE TITLE
Add SoundCraft: Shows: Save *

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-soundcraft-ui#97]
Would it be possible to add functions to save and update SNAPSHOTS and CUES please?

`SoundCraft: Shows: Save Snapshot`
* Input form for Snapshot name. When the same as existing, it will repleace it.

`SoundCraft: Shows: Save Cues`
* Input form for cue name. When the same as existing, it will repleace it.

Thank you.

**Comment by fmalcher** [comment]
Yes, that's already implemented and should be part of the next Companion release. 🙂

**Comment by Suenee** [comment]
In which version please? What is the name of the function? Currently, I only found the `Load Cue` command.

**Comment by fmalcher** [comment]
This will be part of the next minor version (3.x). Actually, I don't know when this will be released, but I suppose it to be within thr next 3 months. You van already install the beta 3.5.0-beta where the module should be included.
